name: hamap
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _tflow_select=2.1.0
  - absl-py=1.3.0
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - astor=0.8.1
  - asttokens=2.2.1
  - astunparse=1.6.3
  - async-timeout=4.0.2
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - blas=1.0
  - blinker=1.4
  - bottleneck=1.3.4
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotlipy=0.7.0
  - c-ares=1.18.1
  - ca-certificates=2024.2.2
  - cachetools=4.2.2
  - cairo=1.16.0
  - certifi=2024.2.2
  - cffi=1.15.0
  - charset-normalizer=2.0.4
  - click=8.0.4
  - cryptography=39.0.1
  - cudatoolkit=10.1.243
  - cudnn=7.6.5
  - cupti=10.1.168
  - debugpy=1.6.7
  - decorator=5.1.1
  - entrypoints=0.4
  - executing=1.2.0
  - expat=2.5.0
  - fontconfig=2.14.2
  - freetype=2.12.1
  - frozenlist=1.2.0
  - gast=0.4.0
  - gdk-pixbuf=2.42.10
  - glib=2.69.1
  - google-auth=2.6.0
  - google-auth-oauthlib=0.4.4
  - google-pasta=0.2.0
  - grpcio=1.42.0
  - h5py=2.10.0
  - hdf5=1.10.6
  - icu=58.2
  - idna=3.4
  - importlib-metadata=6.0.0
  - intel-openmp=2021.4.0
  - ipykernel=6.14.0
  - ipython=8.4.0
  - jbig=2.1
  - jedi=0.18.2
  - jpeg=9e
  - jupyter_client=7.4.9
  - jupyter_core=5.3.0
  - keras-preprocessing=1.1.2
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libdeflate=1.8
  - libexpat=2.5.0
  - libffi=3.3
  - libgcc-ng=12.2.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=12.2.0
  - libpng=1.6.39
  - libprotobuf=3.20.1
  - libsodium=1.0.18
  - libstdcxx-ng=12.2.0
  - libtiff=4.3.0
  - libuuid=2.38.1
  - libwebp-base=1.3.0
  - libxcb=1.13
  - libxml2=2.9.14
  - libzlib=1.2.13
  - littleutils=0.2.2
  - markdown=3.4.1
  - markupsafe=2.1.1
  - matplotlib-base=3.5.3
  - matplotlib-inline=0.1.6
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mpmath=1.3.0
  - multidict=5.2.0
  - munkres=1.1.4
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - numexpr=2.8.1
  - oauthlib=3.2.2
  - olefile=0.46
  - openjpeg=2.5.0
  - openslide=3.4.1
  - openslide-python=1.2.0
  - openssl=1.1.1w
  - opt_einsum=3.3.0
  - outdated=0.2.2
  - packaging=23.0
  - pandas=1.4.2
  - pandas-flavor=0.6.0
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pingouin=0.5.4
  - pip=23.0.1
  - pixman=0.38.0
  - platformdirs=3.2.0
  - prompt-toolkit=3.0.38
  - psutil=5.9.5
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pygments=2.15.1
  - pyjwt=2.4.0
  - pyopenssl=23.0.0
  - pysocks=1.7.1
  - python=3.9.12
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytz=2022.7
  - pyzmq=25.0.2
  - readline=8.1.2
  - requests=2.28.1
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - scikit-learn=1.2.2
  - seaborn-base=0.13.2
  - setuptools=66.0.0
  - six=1.16.0
  - sqlite=3.38.5
  - stack_data=0.6.2
  - statsmodels=0.14.0
  - tabulate=0.9.0
  - tensorboard=2.11.0
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.4.1
  - tensorflow-base=2.4.1
  - tensorflow-estimator=2.6.0
  - tensorflow-gpu=2.4.1
  - termcolor=2.1.0
  - tk=8.6.12
  - tornado=6.3
  - traitlets=5.9.0
  - typing-extensions=4.5.0
  - typing_extensions=4.5.0
  - unicodedata2=15.1.0
  - urllib3=1.26.15
  - wcwidth=0.2.6
  - werkzeug=2.2.3
  - wheel=0.38.4
  - wrapt=1.13.3
  - xarray=2023.2.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yarl=1.6.3
  - zeromq=4.3.4
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - attrs==24.2.0
    - comm==0.1.4
    - contourpy==1.0.7
    - cycler==0.11.0
    - fastjsonschema==2.20.0
    - flatbuffers==24.3.25
    - fonttools==4.39.3
    - imagecodecs==2024.6.1
    - imageio==2.37.0
    - importlib-resources==5.12.0
    - ipywidgets==8.1.1
    - joblib==1.2.0
    - jsonschema==4.23.0
    - jsonschema-specifications==2024.10.1
    - jupyterlab-widgets==3.0.9
    - kaleido==0.2.1
    - kiwisolver==1.4.4
    - krippendorff==0.6.0
    - lazy-loader==0.4
    - libclang==18.1.1
    - matplotlib==3.7.1
    - namex==0.0.8
    - nbformat==5.10.4
    - networkx==3.1
    - numpy==1.22.4
    - opencv-python==4.7.0.72
    - optree==0.12.1
    - patsy==0.5.3
    - pillow==9.5.0
    - plotly==5.24.1
    - protobuf==4.25.4
    - pyarrow==13.0.0
    - pyparsing==3.0.9
    - pywavelets==1.4.1
    - referencing==0.35.1
    - rpds-py==0.20.1
    - scikit-image==0.24.0
    - scikit-misc==0.3.0
    - scipy==1.9.1
    - seaborn==0.12.2
    - spams==2.6.5.4
    - staintools==2.1.2
    - tenacity==9.0.0
    - tensorboard-data-server==0.7.2
    - tensorflow-addons==0.20.0
    - tensorflow-io-gcs-filesystem==0.37.1
    - threadpoolctl==3.1.0
    - tifffile==2023.4.12
    - typeguard==2.13.3
    - tzdata==2024.1
    - widgetsnbextension==4.0.9
prefix: /users/PAS1575/chen8028/anaconda3/envs/CP

